spring:
  application:
    name: A.one
  datasource:
    url: jdbc:mysql://localhost:3306/aone?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: nerosoft.8888
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
server:
  port: 8080